#! /bin/sh

bash ~/.config/bspwm/launch.sh &
wmname LG3D

if [[ $(xrandr -q | grep -w 'DP-1 connected') ]]; then
  xrandr --output eDP-1 --primary --mode 1920x1200 --rotate normal --output DP-1 --mode 1600x900 --rotate normal --right-of eDP-1
  bspc monitor eDP-1 -d I II III IV V 
  bspc monitor DP-1 -d VI VII VIII IX X
else
  bspc monitor -d I II III IV V VI VII VIII IX X
fi 

# bspc monitor -d I II III IV V VI VII VIII IX X 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off



